steps:
- id: "Build GO LANG - gcp "
  name: 'mirror.gcr.io/library/golang'
  env: ['GO111MODULE=on']
  args: ['go','build','soma.go']

- id: "test"
  name: 'mirror.gcr.io/library/golang'
  args: ['go','test', '-v']

- id: "build imagem"
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg'
  - 'version=1.1.0'
  - '-t'
  - 'gcr.io/$PROJECT_ID/desafio-ci-test-golang:latest'
  - '-t'
  - 'gcr.io/$PROJECT_ID/desafio-ci-test-golang:1.1.0'
  - '.'
- name: 'gcr.io/$PROJECT_ID/docker-compose'
  args: ['version']
#images: ['gcr.io/$PROJECT_ID/desafio-ci-test-golang']  
images: 
- 'gcr.io/$PROJECT_ID/desafio-ci-test-golang'